/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Utils.Connect;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author RAVEN
 */
public class Login_1 extends javax.swing.JPanel {

    /**
     * Creates new form Login
     */
    public Login_1() {
        initComponents();
    }

    public void login() {
        txtUser_20.grabFocus();
    }

    public void addEventRegister(ActionListener event) {
        cmdRegister_20.addActionListener(event);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelColor_R1 = new swing.PanelColor_R();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtUser_20 = new swing.MyTextField();
        txtPass_20 = new swing.MyPassword();
        jLabel3 = new javax.swing.JLabel();
        cmdRegister_20 = new javax.swing.JButton();
        myButton1_20 = new swing.MyButton();

        setBackground(new java.awt.Color(204, 255, 255));

        panelColor_R1.setPreferredSize(new java.awt.Dimension(353, 518));

        jLabel2.setFont(new java.awt.Font("sansserif", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(115, 187, 241));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Login");

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("User Name");

        txtUser_20.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N

        txtPass_20.setFont(new java.awt.Font("SansSerif", 0, 10)); // NOI18N
        txtPass_20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPass_20ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");

        cmdRegister_20.setFont(new java.awt.Font("sansserif", 1, 12)); // NOI18N
        cmdRegister_20.setForeground(new java.awt.Color(255, 255, 255));
        cmdRegister_20.setText("Register to now");
        cmdRegister_20.setBorder(null);
        cmdRegister_20.setBorderPainted(false);
        cmdRegister_20.setContentAreaFilled(false);
        cmdRegister_20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        cmdRegister_20.setFocusable(false);
        cmdRegister_20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdRegister_20ActionPerformed(evt);
            }
        });

        myButton1_20.setBackground(new java.awt.Color(8, 103, 123));
        myButton1_20.setForeground(new java.awt.Color(255, 255, 255));
        myButton1_20.setText("Login");
        myButton1_20.setBorderPainted(false);
        myButton1_20.setColor(new java.awt.Color(8, 103, 123));
        myButton1_20.setColorOver(new java.awt.Color(26, 131, 152));
        myButton1_20.setFocusPainted(false);
        myButton1_20.setFocusable(false);
        myButton1_20.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        myButton1_20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButton1_20ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelColor_R1Layout = new javax.swing.GroupLayout(panelColor_R1);
        panelColor_R1.setLayout(panelColor_R1Layout);
        panelColor_R1Layout.setHorizontalGroup(
            panelColor_R1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelColor_R1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(panelColor_R1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelColor_R1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 240, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelColor_R1Layout.createSequentialGroup()
                        .addGroup(panelColor_R1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmdRegister_20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPass_20, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtUser_20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelColor_R1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 191, Short.MAX_VALUE))
                            .addComponent(myButton1_20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(50, 50, 50))))
        );
        panelColor_R1Layout.setVerticalGroup(
            panelColor_R1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelColor_R1Layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtUser_20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(txtPass_20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(myButton1_20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66)
                .addComponent(cmdRegister_20)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelColor_R1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelColor_R1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtPass_20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPass_20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPass_20ActionPerformed

    private void cmdRegister_20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdRegister_20ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmdRegister_20ActionPerformed

    private void myButton1_20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButton1_20ActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        if (txtUser_20.getText().equals("") || txtUser_20.getText().equals("")) {
            sb.append("Mời bạn nhập đầy đủ thông tin");
            JOptionPane.showMessageDialog(this, sb);
        } else {
            try {
                String sql = "Select * from account where taikhoan=? AND matkhau=?";
                Connection con = Connect.getConnection();
                PreparedStatement p = con.prepareStatement(sql);
                p.setString(1, txtUser_20.getText());
                p.setString(2, txtPass_20.getText());
                ResultSet rs = p.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(this, "Đăng Nhập Thành Công");
                    MENU lg = new MENU(txtUser_20.getText());
                    lg.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Sai Username Hoặc Password");
                }
//                con.close();
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_myButton1_20ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdRegister_20;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private swing.MyButton myButton1_20;
    private swing.PanelColor_R panelColor_R1;
    private swing.MyPassword txtPass_20;
    private swing.MyTextField txtUser_20;
    // End of variables declaration//GEN-END:variables
}
