/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Utils.Connect;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author QuanLDM
 */
public class Muon extends javax.swing.JFrame {
    private String dataconstructor;
     private String dataconstructor1;
    public Muon(String data, String data1){
        setTitle("Quản lí thiết bị trường học");
        initComponents();
        this.dataconstructor=data;
        this.dataconstructor1= data1;
        System.out.println(data1);
        jtf_madvc32.setText(data1);
        jtf_madvc32.setEditable(false);
        
    }

    /**
     * Creates new form Muon
     */
    
        
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradiente1 = new swing.PanelGradiente();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtf_mamuon32 = new swing.MyTextField();
        jtf_madvc32 = new swing.MyTextField();
        jtf_manguoi32 = new swing.MyTextField();
        jtf_tennguoi32 = new swing.MyTextField();
        jtf_ngay32 = new swing.MyTextField();
        btn_save32 = new swing.ButtonGradient();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        panelGradiente1.setColorPrimario(new java.awt.Color(107, 222, 248));
        panelGradiente1.setColorSecundario(new java.awt.Color(8, 103, 123));

        jLabel8.setFont(new java.awt.Font("Sitka Display", 1, 36)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 102));
        jLabel8.setText("Mượn thiết bị");
        panelGradiente1.add(jLabel8);
        jLabel8.setBounds(130, 30, 216, 46);

        jLabel2.setText("Ma muon");
        panelGradiente1.add(jLabel2);
        jLabel2.setBounds(70, 130, 50, 13);

        jLabel3.setText("Ma thiet bi");
        panelGradiente1.add(jLabel3);
        jLabel3.setBounds(70, 170, 50, 13);

        jLabel4.setText("Ma nguoi muon");
        panelGradiente1.add(jLabel4);
        jLabel4.setBounds(70, 210, 80, 13);

        jLabel5.setText("Ten nguoi muon");
        panelGradiente1.add(jLabel5);
        jLabel5.setBounds(70, 250, 80, 13);

        jLabel6.setText("Ngay muon");
        panelGradiente1.add(jLabel6);
        jLabel6.setBounds(70, 290, 70, 13);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/previous.png"))); // NOI18N
        jLabel7.setText("Back");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        panelGradiente1.add(jLabel7);
        jLabel7.setBounds(20, 20, 60, 16);
        panelGradiente1.add(jtf_mamuon32);
        jtf_mamuon32.setBounds(180, 120, 180, 27);
        panelGradiente1.add(jtf_madvc32);
        jtf_madvc32.setBounds(180, 160, 180, 27);

        jtf_manguoi32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_manguoi32ActionPerformed(evt);
            }
        });
        panelGradiente1.add(jtf_manguoi32);
        jtf_manguoi32.setBounds(180, 200, 180, 27);
        panelGradiente1.add(jtf_tennguoi32);
        jtf_tennguoi32.setBounds(180, 240, 180, 27);
        panelGradiente1.add(jtf_ngay32);
        jtf_ngay32.setBounds(180, 280, 180, 27);

        btn_save32.setText("Save");
        btn_save32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save32ActionPerformed(evt);
            }
        });
        panelGradiente1.add(btn_save32);
        btn_save32.setBounds(190, 350, 90, 33);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradiente1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelGradiente1, javax.swing.GroupLayout.DEFAULT_SIZE, 417, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        QuanLi_Device s= new QuanLi_Device(dataconstructor);
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jtf_manguoi32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_manguoi32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_manguoi32ActionPerformed

    private void btn_save32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save32ActionPerformed
        // TODO add your handling code here:
        try {
           Connection con = Connect.getConnection();
            String sql = "insert into muon values(?,?,?,?,?,?)";
            String sql1="update thietbi set trangthai=1 where ma='"+dataconstructor1+"'";
            PreparedStatement pstmt = con.prepareStatement(sql);
            PreparedStatement pstmt1 = con.prepareStatement(sql1);
            pstmt.setString(1, jtf_mamuon32.getText());
            pstmt.setString(2, dataconstructor1);
            pstmt.setString(3, jtf_manguoi32.getText());
            pstmt.setString(4, jtf_tennguoi32.getText());
            pstmt.setString(5, jtf_ngay32.getText());
            pstmt.setString(6, null);
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Đăng ký mượn thành công");
           pstmt1.executeUpdate();
            con.close();
            QuanLi_Device s=new QuanLi_Device(dataconstructor);
                s.setVisible(true);
                dispose();
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_save32ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Muon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Muon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Muon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Muon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ButtonGradient btn_save32;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private swing.MyTextField jtf_madvc32;
    private swing.MyTextField jtf_mamuon32;
    private swing.MyTextField jtf_manguoi32;
    private swing.MyTextField jtf_ngay32;
    private swing.MyTextField jtf_tennguoi32;
    private swing.PanelGradiente panelGradiente1;
    // End of variables declaration//GEN-END:variables
}
