/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Utils.Connect;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author QuanLDM
 */
public class Add extends javax.swing.JFrame {
    private static String dataconstructor;
     ResultSet rs = null;
 
    /**
     * Creates new form Add
     */
    public Add(String data) {
        initComponents();
        setTitle("Quản lí thiết bị trường học");
        this.dataconstructor=data;
         try {
            Connection con = Connect.getConnection();
            String sql= "SELECT * FROM loaithietbi  ";
            PreparedStatement pstmt = con.prepareStatement(sql);
            rs = pstmt.executeQuery();
            while(rs.next()){
                cb.addItem(rs.getString("tenloaidvc"));
            }    
        } catch (Exception e) {
            
        }
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradiente1 = new swing.PanelGradiente();
        ma32 = new swing.MyTextField();
        ten32 = new swing.MyTextField();
        jLabel3 = new javax.swing.JLabel();
        cb = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Jbutton_20_save = new swing.ButtonGradient();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelGradiente1.setColorPrimario(new java.awt.Color(107, 222, 248));
        panelGradiente1.setColorSecundario(new java.awt.Color(8, 103, 123));
        panelGradiente1.add(ma32);
        ma32.setBounds(170, 140, 170, 27);
        panelGradiente1.add(ten32);
        ten32.setBounds(170, 180, 170, 27);

        jLabel3.setFont(new java.awt.Font("Sitka Display", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 102));
        jLabel3.setText("Thêm thiết bị");
        panelGradiente1.add(jLabel3);
        jLabel3.setBounds(150, 50, 206, 46);

        panelGradiente1.add(cb);
        cb.setBounds(170, 230, 170, 21);

        jLabel1.setText("Ma thiet bi");
        panelGradiente1.add(jLabel1);
        jLabel1.setBounds(100, 140, 60, 13);

        jLabel2.setText("Ten thiet bi");
        panelGradiente1.add(jLabel2);
        jLabel2.setBounds(110, 190, 50, 13);

        jLabel5.setText("Loai");
        panelGradiente1.add(jLabel5);
        jLabel5.setBounds(120, 240, 30, 10);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/previous.png"))); // NOI18N
        jLabel7.setText("Back");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        panelGradiente1.add(jLabel7);
        jLabel7.setBounds(10, 10, 60, 16);

        Jbutton_20_save.setText("save");
        Jbutton_20_save.setFont(new java.awt.Font("SansSerif", 2, 12)); // NOI18N
        Jbutton_20_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbutton_20_saveActionPerformed(evt);
            }
        });
        panelGradiente1.add(Jbutton_20_save);
        Jbutton_20_save.setBounds(190, 290, 67, 37);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGradiente1, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelGradiente1, javax.swing.GroupLayout.DEFAULT_SIZE, 383, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        QuanLi_Device s=new QuanLi_Device(dataconstructor);
                s.setVisible(true);
                dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void Jbutton_20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbutton_20ActionPerformed
      
    }//GEN-LAST:event_Jbutton_20ActionPerformed

    private void Jbutton_20_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbutton_20_saveActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        // TODO add your handling code here:
        StringBuilder sb= new StringBuilder();
        if (ma32.getText().equals("")||ten32.getText().equals("")){
            sb.append("Please enter all the data");
            JOptionPane.showMessageDialog(this,sb);
        }
        else{
        try {

            Connection con = Connect.getConnection();
            String sql = "insert into thietbi values(?,?,?,?,?)";
            PreparedStatement pstmt = con.prepareStatement(sql);
            pstmt.setString(1, ma32.getText());
            pstmt.setString(2, ten32.getText());
            String lo;
            lo = cb.getSelectedItem().toString();
            pstmt.setString(3, lo);
            pstmt.setString(4, "Normal");
            pstmt.setString(5, "0");
            pstmt.executeUpdate();
            JOptionPane.showMessageDialog(null, "Successful");
            con.close();
            QuanLi_Device s=new QuanLi_Device(dataconstructor);
                s.setVisible(true);
                dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_Jbutton_20_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Add s = new Add(dataconstructor);
                s.setVisible(true);
                
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ButtonGradient Jbutton_20_save;
    private javax.swing.JComboBox<String> cb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private swing.MyTextField ma32;
    private swing.PanelGradiente panelGradiente1;
    private swing.MyTextField ten32;
    // End of variables declaration//GEN-END:variables
}
