/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Utils.Connect;
import com.mysql.cj.xdevapi.Result;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author QuanLDM
 */
public class Infor extends javax.swing.JFrame {

    private static String dataconstructor = "";

    /**
     * Creates new form Infor
     */
    public Infor(String data) {
        setTitle("Quản lí thiết bị trường học");
        initComponents();
        this.dataconstructor = data;
        
        jtf_username32.setEditable(false);
        jtf_password32.setEditable(false);
        jtf_username32.setText(data);
        try {
            Connection con = Connect.getConnection();
            String sql = "select * from account where taikhoan='" + dataconstructor + "'";
            PreparedStatement pstmt = con.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            while (rs.next()) {
                jtf_username32.setText(rs.getString(1));
                jtf_password32.setText(rs.getString(2));
                jtf_email32.setText(rs.getString(3));
                jtf_gender32.setText(rs.getString(4));
                jtf_name32.setText(rs.getString(5));
                jtf_bd32.setText(rs.getString(6));
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradiente1 = new swing.PanelGradiente();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtf_username32 = new swing.MyTextField();
        jtf_email32 = new swing.MyTextField();
        jtf_gender32 = new swing.MyTextField();
        jtf_name32 = new swing.MyTextField();
        jtf_bd32 = new swing.MyTextField();
        jtf_password32 = new swing.MyPassword();
        btn_20_pass = new swing.ButtonGradient();
        btn_20_update = new swing.ButtonGradient();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelGradiente1.setColorSecundario(new java.awt.Color(107, 222, 248));
        panelGradiente1.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Sitka Display", 1, 30)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 102, 102));
        jLabel9.setText("Thông tin người dùng");
        panelGradiente1.add(jLabel9);
        jLabel9.setBounds(120, 20, 340, 38);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setText("Username");
        panelGradiente1.add(jLabel1);
        jLabel1.setBounds(100, 100, 70, 17);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Email");
        panelGradiente1.add(jLabel3);
        jLabel3.setBounds(100, 190, 70, 17);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setText("Password");
        panelGradiente1.add(jLabel2);
        jLabel2.setBounds(100, 150, 70, 17);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Gender");
        panelGradiente1.add(jLabel4);
        jLabel4.setBounds(100, 240, 70, 17);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Name");
        panelGradiente1.add(jLabel6);
        jLabel6.setBounds(100, 290, 70, 17);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel5.setText("Birthday");
        panelGradiente1.add(jLabel5);
        jLabel5.setBounds(100, 340, 80, 17);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/previous.png"))); // NOI18N
        jLabel7.setText("Back");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        panelGradiente1.add(jLabel7);
        jLabel7.setBounds(20, 10, 60, 16);

        jtf_username32.setText("myTextField1");
        panelGradiente1.add(jtf_username32);
        jtf_username32.setBounds(210, 100, 170, 27);

        jtf_email32.setText("myTextField3");
        panelGradiente1.add(jtf_email32);
        jtf_email32.setBounds(210, 190, 170, 27);

        jtf_gender32.setText("myTextField4");
        panelGradiente1.add(jtf_gender32);
        jtf_gender32.setBounds(210, 240, 170, 27);

        jtf_name32.setText("myTextField5");
        panelGradiente1.add(jtf_name32);
        jtf_name32.setBounds(210, 290, 170, 27);

        jtf_bd32.setText("myTextField6");
        panelGradiente1.add(jtf_bd32);
        jtf_bd32.setBounds(210, 340, 170, 27);

        jtf_password32.setText("myPassword1");
        panelGradiente1.add(jtf_password32);
        jtf_password32.setBounds(210, 140, 170, 27);

        btn_20_pass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exchange.png"))); // NOI18N
        btn_20_pass.setText("Change pass");
        btn_20_pass.setColor1(new java.awt.Color(56, 239, 125));
        btn_20_pass.setColor2(new java.awt.Color(17, 153, 142));
        btn_20_pass.setFocusable(false);
        btn_20_pass.setFont(new java.awt.Font("SansSerif", 2, 10)); // NOI18N
        btn_20_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_20_passActionPerformed(evt);
            }
        });
        panelGradiente1.add(btn_20_pass);
        btn_20_pass.setBounds(270, 420, 130, 37);

        btn_20_update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/exchange.png"))); // NOI18N
        btn_20_update.setText("Cập nhật");
        btn_20_update.setFocusable(false);
        btn_20_update.setFont(new java.awt.Font("SansSerif", 2, 10)); // NOI18N
        btn_20_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_20_updateActionPerformed(evt);
            }
        });
        panelGradiente1.add(btn_20_update);
        btn_20_update.setBounds(100, 420, 130, 37);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradiente1, javax.swing.GroupLayout.PREFERRED_SIZE, 506, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradiente1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        MENU s=new MENU(dataconstructor);
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void buttonGradient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient1ActionPerformed
    
    }//GEN-LAST:event_buttonGradient1ActionPerformed

    private void btn_20_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_20_updateActionPerformed
        // TODO add your handling code here:
        try {
           Connection con = Connect.getConnection();
            String sql = "UPDATE account set email='" + jtf_email32.getText() + "' ,gioitinh='" + jtf_gender32.getText() + "',ten='" + jtf_name32.getText() + "' ,ngaysinh='" + jtf_bd32.getText() + "' WHERE taikhoan='" + jtf_username32.getText() + "'";
            PreparedStatement pstmt = con.prepareStatement(sql);
            pstmt = con.prepareStatement(sql);
            pstmt.execute();
            JOptionPane.showMessageDialog(this, "Chỉnh sửa thành công ");
            con.close();
            Infor s = new Infor(dataconstructor);
            s.setVisible(true);
            dispose();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

        
    }//GEN-LAST:event_btn_20_updateActionPerformed

    private void btn_20_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_20_passActionPerformed
         ChangePassword s = new ChangePassword(dataconstructor);
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_btn_20_passActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Infor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Infor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Infor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Infor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Infor in4 = new Infor(dataconstructor);
                in4.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private swing.ButtonGradient btn_20_pass;
    private swing.ButtonGradient btn_20_update;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private swing.MyTextField jtf_bd32;
    private swing.MyTextField jtf_email32;
    private swing.MyTextField jtf_gender32;
    private swing.MyTextField jtf_name32;
    private swing.MyPassword jtf_password32;
    private swing.MyTextField jtf_username32;
    private swing.PanelGradiente panelGradiente1;
    // End of variables declaration//GEN-END:variables
}
