/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author QuanLDM
 */
public class MENU extends javax.swing.JFrame {

    private static String dataConstructor = "";
    private static String dataConstructor2 = "";

    /**
     * Creates new form LIBRARYALL
     */
    public MENU(String dataConstructor) {
        initComponents();
        setTitle("Quản lí thiết bị trường học");
        this.dataConstructor = dataConstructor;
        Name32.setText("  Welcome " + dataConstructor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelGradiente1 = new swing.PanelGradiente();
        Name32 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        List32 = new javax.swing.JLabel();
        ListMuon32 = new javax.swing.JLabel();
        History32 = new javax.swing.JLabel();
        buttonGradient1 = new swing.ButtonGradient();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(79, 228, 228));
        setUndecorated(true);

        panelGradiente1.setColorPrimario(new java.awt.Color(107, 222, 248));

        Name32.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Name32.setForeground(new java.awt.Color(204, 51, 0));
        Name32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/profile.png"))); // NOI18N
        Name32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Name32MouseClicked(evt);
            }
        });
        panelGradiente1.add(Name32);
        Name32.setBounds(50, 20, 32, 32);

        jLabel6.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 153));
        jLabel6.setText("Lịch sử mượn");
        panelGradiente1.add(jLabel6);
        jLabel6.setBounds(580, 160, 170, 31);

        jLabel3.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 153));
        jLabel3.setText("Danh sách mượn");
        panelGradiente1.add(jLabel3);
        jLabel3.setBounds(320, 160, 179, 31);

        jLabel2.setFont(new java.awt.Font("Sitka Subheading", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("Danh sách thiết bị");
        panelGradiente1.add(jLabel2);
        jLabel2.setBounds(60, 160, 190, 31);

        List32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/device.png"))); // NOI18N
        List32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                List32MouseClicked(evt);
            }
        });
        panelGradiente1.add(List32);
        List32.setBounds(90, 220, 128, 128);

        ListMuon32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/thietbi.png"))); // NOI18N
        ListMuon32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListMuon32MouseClicked(evt);
            }
        });
        panelGradiente1.add(ListMuon32);
        ListMuon32.setBounds(340, 220, 128, 128);

        History32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/museum.png"))); // NOI18N
        History32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                History32MouseClicked(evt);
            }
        });
        panelGradiente1.add(History32);
        History32.setBounds(600, 220, 128, 128);

        buttonGradient1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/logout.png"))); // NOI18N
        buttonGradient1.setText("Đăng Xuất");
        buttonGradient1.setColor1(new java.awt.Color(255, 107, 107));
        buttonGradient1.setColor2(new java.awt.Color(85, 98, 112));
        buttonGradient1.setFocusable(false);
        buttonGradient1.setFont(new java.awt.Font("SansSerif", 2, 10)); // NOI18N
        buttonGradient1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGradient1ActionPerformed(evt);
            }
        });
        panelGradiente1.add(buttonGradient1);
        buttonGradient1.setBounds(670, 20, 113, 33);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradiente1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 803, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGradiente1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void List32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_List32MouseClicked
        QuanLi_Device s = new QuanLi_Device(dataConstructor);
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_List32MouseClicked

    private void ListMuon32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListMuon32MouseClicked
        Muon_Device s = new Muon_Device(dataConstructor);
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_ListMuon32MouseClicked

    private void Name32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Name32MouseClicked
        Infor s = new Infor(dataConstructor);
        s.setVisible(true);
        dispose();

//       ChangePassword s= new ChangePassword(dataConstructor);
//       s.setVisible(true);
//       dispose();
    }//GEN-LAST:event_Name32MouseClicked

    private void History32MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_History32MouseClicked
        LichSu_Device s = new LichSu_Device(dataConstructor,dataConstructor2);
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_History32MouseClicked

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        // TODO add your handling code here:
                Main s = new Main();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_bt1ActionPerformed

    private void buttonGradient1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGradient1ActionPerformed
        // TODO add your handling code here:
         Login_1 s = new Login_1();
        s.setVisible(true);
        dispose();
    }//GEN-LAST:event_buttonGradient1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MENU.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MENU mnu = new MENU(dataConstructor);
                mnu.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel History32;
    private javax.swing.JLabel List32;
    private javax.swing.JLabel ListMuon32;
    private javax.swing.JLabel Name32;
    private swing.ButtonGradient buttonGradient1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private swing.PanelGradiente panelGradiente1;
    // End of variables declaration//GEN-END:variables
}
